---
- name: Set up containerd crt and flags
  become: yes
  vars:
    cert: "{{ lookup('env', 'CERT_ID') }}"
    virtcars: "{{ lookup('env', 'VM') }}"
  hosts: "{{ virtcars }}"
  tasks:

    - name: Copy crt
      copy:
        src: "/{{ cert }}.crt"
        dest: "/etc/ssl/certs/{{ cert }}.crt"

    - name: Reload containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
